# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 959aff490af9ce90b90b5d342f4c837d60b36f74bc00562394b78630f40e7be3e2164a08e43c7a363af67e2f988f495008d2c34d6b101ab845e4e1e6f4833d15

test:
  secret_key_base: ce7ec0ee45cbb14d7a40de30907f3eea0e1aa3e3d6d42e0db49f7c20729f1624e1eff6e49aa601221e5cb1d37dd928333137088eda68f040ae0be7b733f0cc3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
